export async function GET() {
  const data = [
    { name: "Kalung Layer", price: 90000, image: "/Kalung Layer.jpg" },
    { name: "Gelang Kulit", price: 130000, image: "/Gelang Kulit.jpg" },
    { name: "Cincin Silver", price: 130000, image: "/Cincin Silver.webp" },
    { name: "Anting Fashion", price: 100000, image: "/Anting Fashion.jpg" },
    { name: "Cardigan Panjang", price: 100000, image: "/Cardigan Panjang.jpg" },
    { name: "Jogger Pants", price: 120000, image: "/Jogger Pants.jpg" },
    { name: "Mantel Musim Dingin", price: 130000, image: "/Mantel Musim Dingin.jpg" },
    { name: "Rompi Kasual", price: 120000, image: "/Rompi Kasual.jpg" },
    { name: "Sandal Flat", price: 130000, image: "/Sandal Flat.jpg" },
    { name: "Sandal Jepit", price: 90000, image: "/Sandal Jepit.jpg" },
    { name: "Shirt Dress", price: 90000, image: "/Shirt Dress.jpg" },
    { name: "Scarf Polos", price: 100000, image: "/Scarf Polos.jpg" },
    { name: "Kipas Tangan", price: 130000, image: "/Kipas Tangan.jpg" },
    { name: "Kacamata Fashion", price: 130000, image: "/Kacamata Fashion.jpg" },
    { name: "Jam Tangan Casual", price: 110000, image: "/Jam Tangan Casual.png" },
    { name: "Ikat Pinggang Kulit", price: 110000, image: "/Ikat Pinggang Kulit.jpg" },
    { name: "Hijab Voal", price: 100000, image: "/Hijab Voal.png" },
    { name: "Dompet Kulit", price: 110000, image: "/Dompet Kulit.jpg" },
    { name: "Topi Bucket", price: 110000, image: "/Topi Bucket.jpg" },
    { name: "Tas Mini Backpack", price: 100000, image: "/Tas Mini Backpack.jpg" },
    { name: "Wedges", price: 110000, image: "/Wedges.png" },
    { name: "Sneakers Canvas", price: 90000, image: "/Sneakers Canvas.jpg" },
    { name: "Slip On Wanita", price: 130000, image: "/Slip On Wanita.jpg" },
    { name: "Slip On Casual", price: 120000, image: "/Slip On Casual.webp" },
    { name: "Sepatu Running", price: 130000, image: "/Sepatu Running.jpg" },
    { name: "Sepatu Platform", price: 120000, image: "/Sepatu Platform.webp" },
    { name: "Sepatu Formal", price: 110000, image: "/Sepatu Formal.webp" },
    { name: "Loafers Pria", price: 110000, image: "/Loafers Pria.webp" },
    { name: "High Heels", price: 90000, image: "/High Heels.webp" },
    { name: "Boots Kulit", price: 90000, image: "/Boots Kulit.jpg" },
    { name: "Espadrilles", price: 120000, image: "/Espadrilles.jpg" },
    { name: "Windbreaker", price: 120000, image: "/Windbreaker.jpg" },
    { name: "Tank Top", price: 90000, image: "/Tank Top.png" },
    { name: "T-shirt Oversize", price: 130000, image: "/T-shirt Oversize.jpg" },
    { name: "T-shirt Graphic", price: 120000, image: "/T-shirt Graphic.jpg" },
    { name: "Sweater Rajut", price: 110000, image: "/Sweater Rajut.jpg" },
    { name: "Sweater Hoodie", price: 100000, image: "/Sweater Hoodie.webp" },
    { name: "Long T-Shirt", price: 120000, image: "/Long T-Shirt.webp" },
    { name: "Legging Polos", price: 90000, image: "/Legging Polos.jpg" },
    { name: "Legging Sport", price: 100000, image: "/Legging Sport.jpg" },
    { name: "Kemeja Flanel", price: 120000, image: "/Kemeja Flanel.webp" },
    { name: "Kaos Polos", price: 110000, image: "/Kaos Polos.jpg" },
    { name: "Jaket Varsity", price: 100000, image: "/Jaket Varsity.jpg" },
    { name: "Jaket Parasut", price: 90000, image: "/Jaket Parasut.webp" },
    { name: "Jaket Kulit", price: 130000, image: "/Jaket Kulit.jpg" },
    { name: "Jaket Denim", price: 120000, image: "/Jaket Denim.jpg" },
    { name: "Celana Training", price: 120000, image: "/Celana Training.webp" },
    { name: "Celana Jogger Cargo", price: 90000, image: "/Celana Jogger Cargo.webp" },
    { name: "Celana Jeans", price: 130000, image: "/Celana Jeans.webp" },
    { name: "Celana Formal", price: 120000, image: "/Celana Formal.webp" },
    { name: "Celana Chino", price: 110000, image: "/Celana Chino.webp" },
    { name: "Bomber Jacket", price: 130000, image: "/Bomber Jacket.jpg" },
    { name: "Blazer Slim Fit", price: 110000, image: "/Blazer Slim Fit.jpg" },
    { name: "Vest Rajut", price: 100000, image: "/Vest Rajut.jpg" },
    { name: "Kaos Polo", price: 100000, image: "/Kaos Polo.jpg" },
    { name: "Tunik Motif", price: 130000, image: "/Tunik Motif.jpg" },
    { name: "Tunik Muslim", price: 90000, image: "/Tunik Muslim.jpg" },
    { name: "Skirt A-Line", price: 110000, image: "/Skirt A-Line.jpg" },
    { name: "Rok Plisket", price: 110000, image: "/Rok Plisket.jpg" },
    { name: "Culottes", price: 100000, image: "/Culottes.jpg" },
    { name: "Crop Tee", price: 90000, image: "/Crop Tee.jpg" },
    { name: "Blouse Lengan Puff", price: 120000, image: "/Blouse Lengan Puff.jpg" },
    { name: "Trench Coat", price: 120000, image: "/Trench Coat.jpg" },
    { name: "Shorts Denim", price: 100000, image: "/Shorts Denim.jpg" },
    { name: "Parka Hoodie", price: 100000, image: "/Parka Hoodie.jpg" },
    { name: "Outer Kimono", price: 90000, image: "/Outer Kimono.jpg" },
    { name: "Celana Kulot", price: 100000, image: "/Celana Kulot.jpg" },
    { name: "Celana Palazzo", price: 110000, image: "/Celana Palazzo.jpg" },
  ];

  // Tambahkan ID berurutan otomatis
  const dataWithId = data.map((item, index) => ({
    id: index + 1,
    ...item,
  }));

  // Return response JSON valid
  return new Response(JSON.stringify(dataWithId), {
    headers: { "Content-Type": "application/json" },
  });
}
